# Generated by Django 4.2.2 on 2023-06-27 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT', '0004_alter_orders_enquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='Enquiry',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='member',
        ),
    ]
